  name: Build-2x Action WorkFlows
  on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
      paths-ignore:
        - '*.md'
        - '*.yml'
        - 'docs/**'

  jobs:
    build-binaries:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@master
          with:
            repository: berlinsaint/containerfiles 

        - name: Setup Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17

        - name: Buildah Action
          uses: redhat-actions/buildah-build@v2
          with:
            image: paddle 
            tags: v1 ${{ github.sha }}
            workdir: paddle
            containerfiles: |
              ./Containerfile
            build-args: |
              some_arg=some_value

        - name: Building 
          run: |
            ls  
            buildah --help
          




